# This is a basic workflow to help you get started with Actions

name: Tests the task on child_process

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Prepare space
        run: rm -rf archives/*
      - name: Install dependencies
        run: |
          npm i
          npm i -g wait-on
      - name: Start server
        run: npm run dev & wait-on http://localhost:3000
      - name: Send request
        run: curl -X POST http://localhost:3000/api/archive
      - name: Check archives
        run: |
          sleep 1
          ls -la ./archives/archive_$(date +%Y-%m-%d)*zip
      - name: Check zip content
        run: |
          checkList=('2023-03/data_0' '2023-05/data_0')
          for element in ${checkList[*]}
          do
            unzip -l ./archives/*zip | grep $element
          done
      - name: Stop server
        run: kill $(lsof -t -i:3000)
  
        
